import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from './ui/card';
import { Badge } from './ui/badge';
import { Button } from './ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select';
import { Slider } from './ui/slider';
import { BarChart, Bar, LineChart, Line, XAxis, YAxis, CartesianGrid, ResponsiveContainer, Legend, Tooltip as RechartsTooltip } from 'recharts';
import { TrendingUp, AlertCircle, Sparkles, MapPin, Users, Clock, Filter } from 'lucide-react';

export function CaseAnalytics() {
  const [dateRange, setDateRange] = useState('month');
  const [heatmapEnabled, setHeatmapEnabled] = useState(false);
  const [timeSliderValue, setTimeSliderValue] = useState([6]); // Last 6 months

  // Section 1: Case Distribution Data
  const casesByType = [
    { type: 'Cybercrime', count: 24, color: '#3b82f6' },
    { type: 'Fraud', count: 18, color: '#f59e0b' },
    { type: 'Drug Crime', count: 15, color: '#ef4444' },
    { type: 'Theft', count: 12, color: '#8b5cf6' },
    { type: 'Assault', count: 9, color: '#10b981' },
  ];

  const openVsClosedData = [
    { month: 'Jan', open: 42, closed: 38 },
    { month: 'Feb', open: 45, closed: 41 },
    { month: 'Mar', open: 48, closed: 39 },
    { month: 'Apr', open: 52, closed: 44 },
    { month: 'May', open: 49, closed: 47 },
    { month: 'Jun', open: 56, closed: 42 },
  ];

  // Section 2: SLA & Resolution Performance Data
  const slaComplianceData = [
    { week: 'W1', compliance: 87 },
    { week: 'W2', compliance: 82 },
    { week: 'W3', compliance: 79 },
    { week: 'W4', compliance: 85 },
    { week: 'W5', compliance: 88 },
    { week: 'W6', compliance: 84 },
  ];

  const avgResolutionTimeData = [
    { week: 'W1', days: 14.2 },
    { week: 'W2', days: 15.8 },
    { week: 'W3', days: 16.5 },
    { week: 'W4', days: 14.9 },
    { week: 'W5', days: 13.7 },
    { week: 'W6', days: 14.3 },
  ];

  const bottleneckStages = [
    { stage: 'Forensics Analysis', avgDelay: '3.2 days', impact: 'High', cases: 24 },
    { stage: 'Pending Approvals', avgDelay: '2.1 days', impact: 'Medium', cases: 18 },
    { stage: 'Task Assignment', avgDelay: '1.5 days', impact: 'Medium', cases: 15 },
    { stage: 'Evidence Collection', avgDelay: '0.8 days', impact: 'Low', cases: 9 },
  ];

  // Section 3: Geo Analysis Data
  const geoCaseData = [
    { district: 'District 1', cases: 12, lat: 35, lng: 25, severity: 'medium' },
    { district: 'District 2', cases: 8, lat: 45, lng: 35, severity: 'low' },
    { district: 'District 3', cases: 21, lat: 55, lng: 45, severity: 'high' },
    { district: 'District 4', cases: 28, lat: 25, lng: 55, severity: 'critical' },
    { district: 'District 5', cases: 15, lat: 65, lng: 65, severity: 'medium' },
  ];

  // Section 4: Investigator Load Data
  const investigatorData = [
    { name: 'Det. Sarah Chen', activeCases: 8, avgResolution: '12.3 days', overload: false },
    { name: 'Det. Marcus Webb', activeCases: 12, avgResolution: '15.8 days', overload: true },
    { name: 'Det. Lisa Park', activeCases: 7, avgResolution: '11.2 days', overload: false },
    { name: 'Det. James Cooper', activeCases: 11, avgResolution: '14.5 days', overload: true },
    { name: 'Det. Angela Torres', activeCases: 9, avgResolution: '13.1 days', overload: false },
  ];

  const getImpactColor = (impact: string) => {
    if (impact === 'High') return 'bg-red-500/20 text-red-400 border-red-500/30';
    if (impact === 'Medium') return 'bg-amber-500/20 text-amber-400 border-amber-500/30';
    return 'bg-green-500/20 text-green-400 border-green-500/30';
  };

  const getSeverityColor = (severity: string) => {
    if (severity === 'critical') return 'bg-red-500';
    if (severity === 'high') return 'bg-orange-500';
    if (severity === 'medium') return 'bg-amber-500';
    return 'bg-blue-500';
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="space-y-2">
        <h1 className="text-white">Case Analytics</h1>
        <p className="text-slate-400">
          Analytical view of trends, workload, and risk across your cases.
        </p>
        <div className="flex items-center gap-2 mt-2">
          <Sparkles className="w-4 h-4 text-cyan-400" />
          <p className="text-cyan-300 text-sm">
            Insights generated by AI, validated by operational data.
          </p>
        </div>
      </div>

      {/* Date Range Filter */}
      <Card className="bg-slate-900/50 border-slate-800">
        <CardContent className="pt-6">
          <div className="flex items-center gap-4">
            <Filter className="w-5 h-5 text-slate-400" />
            <div className="flex-1 max-w-xs">
              <Select value={dateRange} onValueChange={setDateRange}>
                <SelectTrigger className="bg-slate-950/50 border-slate-700 text-white">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent className="bg-slate-900 border-slate-700">
                  <SelectItem value="week">Last Week</SelectItem>
                  <SelectItem value="month">Last Month</SelectItem>
                  <SelectItem value="quarter">Last Quarter</SelectItem>
                  <SelectItem value="year">Last Year</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        {/* Main Analytics Content */}
        <div className="lg:col-span-3 space-y-6">
          {/* SECTION 1: CASE DISTRIBUTION & TRENDS */}
          <div className="space-y-4">
            <h2 className="text-white flex items-center gap-2">
              <TrendingUp className="w-5 h-5 text-blue-400" />
              Case Distribution & Trends
            </h2>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {/* Cases by Type */}
              <Card className="bg-slate-900/50 border-slate-800">
                <CardHeader>
                  <CardTitle className="text-white text-base">Cases by Type</CardTitle>
                  <p className="text-slate-400 text-xs">Click a bar to filter cases</p>
                </CardHeader>
                <CardContent>
                  <ResponsiveContainer width="100%" height={240}>
                    <BarChart data={casesByType}>
                      <CartesianGrid strokeDasharray="3 3" stroke="#334155" />
                      <XAxis dataKey="type" stroke="#94a3b8" style={{ fontSize: '11px' }} angle={-15} textAnchor="end" height={70} />
                      <YAxis stroke="#94a3b8" style={{ fontSize: '12px' }} />
                      <RechartsTooltip
                        contentStyle={{ backgroundColor: '#1e293b', border: '1px solid #475569', borderRadius: '8px' }}
                        labelStyle={{ color: '#cbd5e1' }}
                        itemStyle={{ color: '#3b82f6' }}
                      />
                      <Bar dataKey="count" fill="#3b82f6" cursor="pointer" />
                    </BarChart>
                  </ResponsiveContainer>
                </CardContent>
              </Card>

              {/* Open vs Closed Over Time */}
              <Card className="bg-slate-900/50 border-slate-800">
                <CardHeader>
                  <CardTitle className="text-white text-base">Open vs Closed Over Time</CardTitle>
                  <p className="text-slate-400 text-xs">Click a point to filter cases</p>
                </CardHeader>
                <CardContent>
                  <ResponsiveContainer width="100%" height={240}>
                    <LineChart data={openVsClosedData}>
                      <CartesianGrid strokeDasharray="3 3" stroke="#334155" />
                      <XAxis dataKey="month" stroke="#94a3b8" style={{ fontSize: '12px' }} />
                      <YAxis stroke="#94a3b8" style={{ fontSize: '12px' }} />
                      <Legend wrapperStyle={{ fontSize: '12px' }} />
                      <RechartsTooltip
                        contentStyle={{ backgroundColor: '#1e293b', border: '1px solid #475569', borderRadius: '8px' }}
                        labelStyle={{ color: '#cbd5e1' }}
                      />
                      <Line type="monotone" dataKey="open" stroke="#f59e0b" strokeWidth={2} name="Open" cursor="pointer" />
                      <Line type="monotone" dataKey="closed" stroke="#10b981" strokeWidth={2} name="Closed" cursor="pointer" />
                    </LineChart>
                  </ResponsiveContainer>
                </CardContent>
              </Card>
            </div>
          </div>

          {/* SECTION 2: SLA & RESOLUTION PERFORMANCE */}
          <div className="space-y-4">
            <h2 className="text-white flex items-center gap-2">
              <Clock className="w-5 h-5 text-blue-400" />
              SLA & Resolution Performance
            </h2>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {/* SLA Compliance Trend */}
              <Card className="bg-slate-900/50 border-slate-800">
                <CardHeader>
                  <CardTitle className="text-white text-base">SLA Compliance Trend</CardTitle>
                  <p className="text-slate-400 text-xs">Weekly compliance percentage</p>
                </CardHeader>
                <CardContent>
                  <ResponsiveContainer width="100%" height={200}>
                    <LineChart data={slaComplianceData}>
                      <CartesianGrid strokeDasharray="3 3" stroke="#334155" />
                      <XAxis dataKey="week" stroke="#94a3b8" style={{ fontSize: '12px' }} />
                      <YAxis stroke="#94a3b8" style={{ fontSize: '12px' }} domain={[70, 100]} />
                      <RechartsTooltip
                        contentStyle={{ backgroundColor: '#1e293b', border: '1px solid #475569', borderRadius: '8px' }}
                        labelStyle={{ color: '#cbd5e1' }}
                      />
                      <Line type="monotone" dataKey="compliance" stroke="#10b981" strokeWidth={2} name="Compliance %" />
                    </LineChart>
                  </ResponsiveContainer>
                </CardContent>
              </Card>

              {/* Avg Resolution Time */}
              <Card className="bg-slate-900/50 border-slate-800">
                <CardHeader>
                  <CardTitle className="text-white text-base">Avg Resolution Time</CardTitle>
                  <p className="text-slate-400 text-xs">Weekly average in days</p>
                </CardHeader>
                <CardContent>
                  <ResponsiveContainer width="100%" height={200}>
                    <LineChart data={avgResolutionTimeData}>
                      <CartesianGrid strokeDasharray="3 3" stroke="#334155" />
                      <XAxis dataKey="week" stroke="#94a3b8" style={{ fontSize: '12px' }} />
                      <YAxis stroke="#94a3b8" style={{ fontSize: '12px' }} domain={[10, 20]} />
                      <RechartsTooltip
                        contentStyle={{ backgroundColor: '#1e293b', border: '1px solid #475569', borderRadius: '8px' }}
                        labelStyle={{ color: '#cbd5e1' }}
                      />
                      <Line type="monotone" dataKey="days" stroke="#f59e0b" strokeWidth={2} name="Avg Days" />
                    </LineChart>
                  </ResponsiveContainer>
                </CardContent>
              </Card>
            </div>

            {/* Bottleneck Stages Table */}
            <Card className="bg-slate-900/50 border-slate-800">
              <CardHeader>
                <CardTitle className="text-white text-base">Bottleneck Stages</CardTitle>
                <p className="text-slate-400 text-xs">Where delays are happening</p>
              </CardHeader>
              <CardContent>
                <div className="overflow-x-auto">
                  <table className="w-full">
                    <thead>
                      <tr className="border-b border-slate-700">
                        <th className="text-left text-slate-300 text-sm py-3 px-4">Stage</th>
                        <th className="text-left text-slate-300 text-sm py-3 px-4">Avg Delay</th>
                        <th className="text-left text-slate-300 text-sm py-3 px-4">Impact</th>
                        <th className="text-left text-slate-300 text-sm py-3 px-4">Affected Cases</th>
                      </tr>
                    </thead>
                    <tbody>
                      {bottleneckStages.map((stage, idx) => (
                        <tr key={idx} className="border-b border-slate-800 hover:bg-slate-800/50 cursor-pointer transition-colors">
                          <td className="text-white text-sm py-3 px-4">{stage.stage}</td>
                          <td className="text-orange-300 text-sm py-3 px-4">{stage.avgDelay}</td>
                          <td className="py-3 px-4">
                            <Badge className={getImpactColor(stage.impact) + ' text-xs'}>
                              {stage.impact}
                            </Badge>
                          </td>
                          <td className="text-slate-300 text-sm py-3 px-4">{stage.cases}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* SECTION 3: GEO ANALYSIS */}
          <div className="space-y-4">
            <h2 className="text-white flex items-center gap-2">
              <MapPin className="w-5 h-5 text-blue-400" />
              Geographic Analysis
            </h2>

            <Card className="bg-slate-900/50 border-slate-800">
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div>
                    <CardTitle className="text-white text-base">Case Density by District</CardTitle>
                    <p className="text-slate-400 text-xs mt-1">Click a region to filter cases</p>
                  </div>
                  <div className="flex items-center gap-4">
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => setHeatmapEnabled(!heatmapEnabled)}
                      className={`text-xs ${heatmapEnabled ? 'bg-blue-600 text-white border-blue-600' : 'border-slate-600 text-slate-300'}`}
                    >
                      Heatmap {heatmapEnabled ? 'On' : 'Off'}
                    </Button>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                {/* Map Visualization */}
                <div className="relative bg-slate-950 rounded-lg border border-slate-700 h-80 overflow-hidden">
                  {/* Simple map representation */}
                  <div className="absolute inset-0 p-6">
                    {geoCaseData.map((district, idx) => (
                      <div
                        key={idx}
                        className="absolute group cursor-pointer"
                        style={{
                          left: `${district.lng}%`,
                          top: `${district.lat}%`,
                          transform: 'translate(-50%, -50%)',
                        }}
                      >
                        {/* District marker */}
                        <div
                          className={`${getSeverityColor(district.severity)} ${heatmapEnabled ? 'opacity-70' : 'opacity-90'} rounded-full flex items-center justify-center transition-all group-hover:scale-110 shadow-lg`}
                          style={{
                            width: `${20 + district.cases}px`,
                            height: `${20 + district.cases}px`,
                          }}
                        >
                          <span className="text-white text-xs">{district.cases}</span>
                        </div>
                        
                        {/* Tooltip on hover */}
                        <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 hidden group-hover:block z-10">
                          <div className="bg-slate-800 border border-slate-600 rounded-lg px-3 py-2 shadow-xl whitespace-nowrap">
                            <p className="text-white text-sm font-semibold">{district.district}</p>
                            <p className="text-slate-300 text-xs">{district.cases} active cases</p>
                            <p className="text-xs mt-1">
                              <span className={`${district.severity === 'critical' ? 'text-red-400' : district.severity === 'high' ? 'text-orange-400' : district.severity === 'medium' ? 'text-amber-400' : 'text-blue-400'}`}>
                                {district.severity.toUpperCase()}
                              </span>
                            </p>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>

                  {/* Legend */}
                  <div className="absolute bottom-4 right-4 bg-slate-900/90 border border-slate-700 rounded-lg p-3">
                    <p className="text-slate-300 text-xs mb-2">Severity</p>
                    <div className="space-y-1">
                      <div className="flex items-center gap-2">
                        <div className="w-3 h-3 bg-red-500 rounded-full"></div>
                        <span className="text-slate-300 text-xs">Critical</span>
                      </div>
                      <div className="flex items-center gap-2">
                        <div className="w-3 h-3 bg-orange-500 rounded-full"></div>
                        <span className="text-slate-300 text-xs">High</span>
                      </div>
                      <div className="flex items-center gap-2">
                        <div className="w-3 h-3 bg-amber-500 rounded-full"></div>
                        <span className="text-slate-300 text-xs">Medium</span>
                      </div>
                      <div className="flex items-center gap-2">
                        <div className="w-3 h-3 bg-blue-500 rounded-full"></div>
                        <span className="text-slate-300 text-xs">Low</span>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Time Slider */}
                <div className="mt-6 px-4">
                  <div className="flex items-center justify-between mb-2">
                    <label className="text-slate-300 text-sm">Time Range</label>
                    <span className="text-blue-400 text-sm">Last {timeSliderValue[0]} months</span>
                  </div>
                  <Slider
                    value={timeSliderValue}
                    onValueChange={setTimeSliderValue}
                    max={12}
                    min={1}
                    step={1}
                    className="w-full"
                  />
                  <div className="flex justify-between text-xs text-slate-500 mt-1">
                    <span>1 month</span>
                    <span>12 months</span>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* SECTION 4: INVESTIGATOR LOAD & PERFORMANCE */}
          <div className="space-y-4">
            <h2 className="text-white flex items-center gap-2">
              <Users className="w-5 h-5 text-blue-400" />
              Investigator Load & Performance
            </h2>

            <Card className="bg-slate-900/50 border-slate-800">
              <CardHeader>
                <CardTitle className="text-white text-base">Team Capacity Overview</CardTitle>
                <p className="text-slate-400 text-xs">Click an investigator to filter their cases</p>
              </CardHeader>
              <CardContent>
                <div className="overflow-x-auto">
                  <table className="w-full">
                    <thead>
                      <tr className="border-b border-slate-700">
                        <th className="text-left text-slate-300 text-sm py-3 px-4">Investigator</th>
                        <th className="text-left text-slate-300 text-sm py-3 px-4">Active Cases</th>
                        <th className="text-left text-slate-300 text-sm py-3 px-4">Avg Resolution Time</th>
                        <th className="text-left text-slate-300 text-sm py-3 px-4">Status</th>
                      </tr>
                    </thead>
                    <tbody>
                      {investigatorData.map((investigator, idx) => (
                        <tr key={idx} className="border-b border-slate-800 hover:bg-slate-800/50 cursor-pointer transition-colors">
                          <td className="text-white text-sm py-3 px-4">{investigator.name}</td>
                          <td className="py-3 px-4">
                            <div className="flex items-center gap-2">
                              <span className="text-blue-300 text-sm">{investigator.activeCases}</span>
                              {/* Heatmap-style indicator */}
                              <div className="flex gap-0.5">
                                {[...Array(12)].map((_, i) => (
                                  <div
                                    key={i}
                                    className={`w-1.5 h-4 rounded-sm ${
                                      i < investigator.activeCases
                                        ? investigator.activeCases >= 11
                                          ? 'bg-red-500'
                                          : investigator.activeCases >= 9
                                          ? 'bg-amber-500'
                                          : 'bg-green-500'
                                        : 'bg-slate-700'
                                    }`}
                                  />
                                ))}
                              </div>
                            </div>
                          </td>
                          <td className="text-slate-300 text-sm py-3 px-4">{investigator.avgResolution}</td>
                          <td className="py-3 px-4">
                            {investigator.overload ? (
                              <Badge className="bg-red-500/20 text-red-400 border-red-500/30 text-xs flex items-center gap-1 w-fit">
                                <AlertCircle className="w-3 h-3" />
                                Overloaded
                              </Badge>
                            ) : (
                              <Badge className="bg-green-500/20 text-green-400 border-green-500/30 text-xs w-fit">
                                Normal
                              </Badge>
                            )}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>

        {/* SECTION 5: AI-NARRATED INSIGHTS (SIDEBAR) */}
        <div className="lg:col-span-1">
          <Card className="bg-gradient-to-br from-cyan-950/40 to-slate-900/40 border-cyan-500/30 shadow-xl shadow-cyan-500/10 sticky top-24">
            <CardHeader>
              <CardTitle className="text-cyan-300 flex items-center gap-2 text-base">
                <Sparkles className="w-5 h-5" />
                AI Insights
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              {/* Insight 1 */}
              <div className="p-3 bg-slate-950/50 rounded-lg border border-cyan-500/30">
                <div className="flex items-start gap-2 mb-2">
                  <TrendingUp className="w-4 h-4 text-orange-400 mt-0.5 flex-shrink-0" />
                  <div className="flex-1">
                    <p className="text-slate-100 text-sm leading-relaxed">
                      Cybercrime cases increased <span className="text-orange-300">18%</span> this week, concentrated in <span className="text-orange-300">District 4</span>. SLA breaches correlate with forensic delays.
                    </p>
                  </div>
                </div>
                <div className="flex items-center justify-between mt-3">
                  <Badge className="bg-green-500/20 text-green-400 border-green-500/30 text-xs">
                    88% confidence
                  </Badge>
                  <Button variant="ghost" size="sm" className="text-xs text-cyan-300 hover:text-cyan-200 h-auto p-0">
                    Explain insight →
                  </Button>
                </div>
              </div>

              {/* Insight 2 */}
              <div className="p-3 bg-slate-950/50 rounded-lg border border-cyan-500/30">
                <div className="flex items-start gap-2 mb-2">
                  <AlertCircle className="w-4 h-4 text-red-400 mt-0.5 flex-shrink-0" />
                  <div className="flex-1">
                    <p className="text-slate-100 text-sm leading-relaxed">
                      Two investigators (<span className="text-red-300">Det. Webb, Det. Cooper</span>) are handling <span className="text-red-300">45%</span> of active cases. Consider rebalancing workload.
                    </p>
                  </div>
                </div>
                <div className="flex items-center justify-between mt-3">
                  <Badge className="bg-green-500/20 text-green-400 border-green-500/30 text-xs">
                    92% confidence
                  </Badge>
                  <Button variant="ghost" size="sm" className="text-xs text-cyan-300 hover:text-cyan-200 h-auto p-0">
                    Explain insight →
                  </Button>
                </div>
              </div>

              {/* Insight 3 */}
              <div className="p-3 bg-slate-950/50 rounded-lg border border-cyan-500/30">
                <div className="flex items-start gap-2 mb-2">
                  <Clock className="w-4 h-4 text-amber-400 mt-0.5 flex-shrink-0" />
                  <div className="flex-1">
                    <p className="text-slate-100 text-sm leading-relaxed">
                      Forensics stage causes <span className="text-amber-300">avg 3.2-day delays</span> across 24 cases. This is <span className="text-amber-300">35% above baseline</span>.
                    </p>
                  </div>
                </div>
                <div className="flex items-center justify-between mt-3">
                  <Badge className="bg-green-500/20 text-green-400 border-green-500/30 text-xs">
                    95% confidence
                  </Badge>
                  <Button variant="ghost" size="sm" className="text-xs text-cyan-300 hover:text-cyan-200 h-auto p-0">
                    Explain insight →
                  </Button>
                </div>
              </div>

              {/* Insight 4 */}
              <div className="p-3 bg-slate-950/50 rounded-lg border border-cyan-500/30">
                <div className="flex items-start gap-2 mb-2">
                  <TrendingUp className="w-4 h-4 text-green-400 mt-0.5 flex-shrink-0" />
                  <div className="flex-1">
                    <p className="text-slate-100 text-sm leading-relaxed">
                      SLA compliance improved to <span className="text-green-300">88%</span> in Week 5, driven by faster task assignment in Fraud cases.
                    </p>
                  </div>
                </div>
                <div className="flex items-center justify-between mt-3">
                  <Badge className="bg-green-500/20 text-green-400 border-green-500/30 text-xs">
                    81% confidence
                  </Badge>
                  <Button variant="ghost" size="sm" className="text-xs text-cyan-300 hover:text-cyan-200 h-auto p-0">
                    Explain insight →
                  </Button>
                </div>
              </div>

              {/* Suggested Actions */}
              <div className="pt-4 border-t border-slate-700">
                <h4 className="text-white text-sm mb-3">Suggested Actions</h4>
                <div className="space-y-2">
                  <Button
                    variant="outline"
                    size="sm"
                    className="w-full justify-start text-xs border-blue-500/50 text-blue-300 hover:bg-blue-950/50"
                  >
                    Filter District 4 cases
                  </Button>
                  <Button
                    variant="outline"
                    size="sm"
                    className="w-full justify-start text-xs border-blue-500/50 text-blue-300 hover:bg-blue-950/50"
                  >
                    View overloaded investigators
                  </Button>
                  <Button
                    variant="outline"
                    size="sm"
                    className="w-full justify-start text-xs border-blue-500/50 text-blue-300 hover:bg-blue-950/50"
                  >
                    Analyze forensic bottleneck
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
